---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: promenade-networking
data:
  release_prefix: promenade
  chart_groups:
    - promenade-networking
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: promenade-networking
data:
  description: core
  sequenced: True
  chart_group:
    - calico
    - kube-dns
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: calico
data:
  chart_name: calico
  release: calico
  namespace: kube-system
  timeout: 600
  values:
    calico:
      etcd:
        credentials:
          ca: |-
{{ config.get(kind='CertificateAuthority', name='calico-etcd-client')['data'] | indent(12, True) }}
          cert: |-
{{ config.get(kind='Certificate', alias='calico-etcd-node-client')['data'] | indent(12, True) }}
          key: |-
{{ config.get(kind='CertificateKey', alias='calico-etcd-node-client')['data'] | indent(12, True) }}
  source:
    type: local
    location: /etc/kubernetes/armada-loader/assets/charts
    subpath: calico
  dependencies: []
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: kube-dns
data:
  chart_name: kube-dns
  release: kube-dns
  namespace: kube-system
  timeout: 600
  values:
    kube_dns:
      replicas: 1
      restartPolicy: Never  # An attempt to work around calico not being ready.
      {%- if config['Network']['dns_servers'] is defined %}
      upstream_nameservers:
      {%- for nameserver in config['Network']['dns_servers'] %}
      - {{ nameserver }}
      {%- endfor %}
      {%- else %}
      upstream_nameservers: []
      {%- endif %}
  source:
    type: local
    location: /etc/kubernetes/armada-loader/assets/charts
    subpath: kube-dns
  dependencies: []
