armada:

  # results in "armada-keystone" release name below
  # to avoid manipulating releases managed directtly
  # with helm or other armadas
  release_prefix: ucp

  charts:
  - description: 'core'
    sequenced: True
    chart_group:
    - chart:
        name: calico
        release_name: calico
        namespace: kube-system
        timeout: 600
        values:
          calico:
            etcd:
              credentials:
                ca: |-
{{ config.get(kind='CertificateAuthority', name='calico-etcd-client')['data'] | indent(18, True) }}
                cert: |-
{{ config.get(kind='Certificate', alias='calico-etcd-node-client')['data'] | indent(18, True) }}
                key: |-
{{ config.get(kind='CertificateKey', alias='calico-etcd-node-client')['data'] | indent(18, True) }}
        source:
          type: local
          location: /etc/kubernetes/armada-loader/assets/charts
          subpath: calico
        dependencies: []

    - chart:
        name: kube-dns
        release_name: kube-dns
        namespace: kube-system
        timeout: 600
        values:
          kube_dns:
            replicas: 1
            {%- if config['Network']['dns_servers'] is defined %}
            upstream_nameservers:
            {%- for nameserver in config['Network']['dns_servers'] %}
            - {{ nameserver }}
            {%- endfor %}
            {%- else %}
            upstream_nameservers: []
            {%- endif %}
        source:
          type: local
          location: /etc/kubernetes/armada-loader/assets/charts
          subpath: kube-dns
        dependencies: []
