- hosts: bootstrap
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - deploy-bootstrap

- hosts: master
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - deploy-kubelet

- hosts: workers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - deploy-kubelet

#- hosts: master
#  remote_user: ubuntu
#  become: yes
#  become_method: sudo
#  roles:
#    - deploy-addons
