---
apiVersion: v1
clusters:
- cluster:
    server: https://kubernetes.default.svc.{{ config['Network']['cluster_domain'] }}
    certificate-authority: /etc/kubernetes/armada-loader/pki/cluster-ca.pem
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: armada-loader
  name: armada-loader@kubernetes
current-context: armada-loader@kubernetes
kind: Config
preferences: {}
users:
- name: armada-loader
  user:
    client-certificate: /etc/kubernetes/armada-loader/pki/armada-loader.pem
    client-key: /etc/kubernetes/armada-loader/pki/armada-loader-key.pem
