---
# The following contains k8s Secrets for use with a TLS enabled etcd cluster.
# For information on populating Secrets, see http://kubernetes.io/docs/user-guide/secrets/
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: calico-etcd-secrets
  namespace: kube-system
data:
  # Populate the following files with etcd TLS configuration if desired, but leave blank if
  # not using TLS for etcd.
  # This self-hosted install expects three files with the following names.  The values
  # should be base64 encoded strings of the entire contents of each file.
  etcd-key: {{ .Values.calico.etcd.credentials.key | b64enc }}
  etcd-cert: {{ .Values.calico.etcd.credentials.cert | b64enc }}
  etcd-ca: {{ .Values.calico.etcd.credentials.ca | b64enc }}
